### ISSUE TITLE
TypeError: Cannot read property 'getAttribute' of null at getMarkdownBodiesAndDatetimes (app.js:8022)

### ISSUE THREAD

**Issue by JuroOravec** [tanmayrajani/notifications-preview-github#92] opened 2020-04-08 10:31 UTC
Tried to use the Chrome extension. I'm getting the following errors:

```
app.js:8022 Uncaught (in promise) TypeError: Cannot read property 'getAttribute' of null
    at getMarkdownBodiesAndDatetimes (app.js:8022)
    at _callee4$ (app.js:7729)
    at tryCatch (app.js:3091)
    at Generator.invoke [as _invoke] (app.js:3329)
    at Generator.prototype.<computed> [as next] (app.js:3143)
    at step (app.js:1693)
    at app.js:1711
    at new Promise (<anonymous>)
    at new F (app.js:978)
    at app.js:1690
```

<details>
<summary>Full Stack Trace</summary>

Call | Location
-- | -- 
getMarkdownBodiesAndDatetimes | app.js:8022
_callee4$ | app.js:7729
tryCatch | app.js:3091
invoke | app.js:3329
prototype.<computed> | app.js:3143
step | app.js:1693
(anonymous) | app.js:1711
F | app.js:978
(anonymous) | app.js:1690
getRootsAndDateTimes | app.js:7744
_callee2$ | app.js:7884
tryCatch | app.js:3091
invoke | app.js:3329
prototype.<computed> | app.js:3143
step | app.js:1693
(anonymous) | app.js:1711
F | app.js:978
(anonymous) | app.js:1690
(anonymous) | app.js:9008
gitHubInjection | app.js:8124
(anonymous) | app.js:9007
Promise.then (async) |  
step | app.js:1703
(anonymous) | app.js:1711
F | app.js:978
(anonymous) | app.js:1690
(anonymous) | app.js:9008
gitHubInjection | app.js:8124
(anonymous) | app.js:9007
Promise.then (async) |  
(anonymous) | app.js:9006
\_\_webpack_require\_\_ | app.js:20
(anonymous) | app.js:66
(anonymous) | app.js:69
</details>

And

```
index.js:48 Uncaught (in promise) TypeError: Cannot read property 'textContent' of null
    at updateUnreadCount (index.js:48)
```

<details>
<summary>Full Stack Trace</summary>

Call | Location
-- | --
updateUnreadCount | index.js:48
async function (async)	|	
updateUnreadCount | index.js:47
updateLoop | index.js:144
async function (async)	|
updateLoop | index.js:142
init | index.js:153
async function (async)	|	
init | index.js:151
(anonymous) | index.js:160

</details>

**Specs**:
Device Type / Model: Desktop or laptop 
Operating System: macOS version 10.15.3 (32-bit) 
Browser: Chrome version 80.0.3987.149 (32-bit) (Engine: Blink)

**Comment by fregante** [comment] 2020-04-22 23:42
Sorry for the experience. The extension was broken due to the new Notifications UI coming out.

The first error is not from this extension while the second error has most likely been fixed in version 20.4.5.

A new version (20.4.24) has just been deployed but Chrome might take a few days to publish it.

I'll close this for now, let me know if the problem is still there with the latest version.

**Closed by fregante** 2020-04-22 23:42 UTC
