### ISSUE TITLE
0.10.1 Just shows swagging does nothing on hover

### ISSUE THREAD

**Issue by yakov116** [tanmayrajani/notifications-preview-github#36] opened 2017-09-13 16:20 UTC
![2017-09-13_12-20-01](https://user-images.githubusercontent.com/16872793/30388497-e20a0d3e-987d-11e7-9cf7-7198da0359ce.gif)

**Comment by yakov116** [comment] 2017-09-13 16:23
In fact its so good at swagging it does even when there are no notifications!
![2017-09-13_12-22-41](https://user-images.githubusercontent.com/16872793/30388659-52328e4c-987e-11e7-9157-04d0160463ed.gif)

**Comment by bfred-it** [comment] 2017-09-13 16:34
Can't reproduce. Do you see any errors? It should only stay like that if a fetch is still happening or if it failed.

**Comment by yakov116** [comment] 2017-09-13 16:36
```
chrome-extension://kgilejfahkjidpaclkepbdoeioeohfmj/index.js:49 Uncaught (in promise) TypeError: elFrom.getAttributeNames(...)[Symbol.iterator] is not a function
    at copyAttributes (chrome-extension://kgilejfahkjidpaclkepbdoeioeohfmj/index.js:49)
    at updateUnreadIndicator (chrome-extension://kgilejfahkjidpaclkepbdoeioeohfmj/index.js:57)
    at fetchNotifications (chrome-extension://kgilejfahkjidpaclkepbdoeioeohfmj/index.js:126)
    at <anonymous>
12:35:58.280 index.js:113 Uncaught (in promise) TypeError: elFrom.getAttributeNames(...)[Symbol.iterator] is not a function
    at copyAttributes (index.js:49)
    at updateUnreadIndicator (index.js:57)
    at fetchNotifications (index.js:126)
    at <anonymous>
```

**Comment by bfred-it** [comment] 2017-09-13 16:36
If you're seeing the dot but not a number, the first fetch definitely failed. (I'll push a fix to stop the animation if it completely fails)

**Comment by bfred-it** [comment] 2017-09-13 16:36
What Chrome version are you using?

**Comment by yakov116** [comment] 2017-09-13 16:37
Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by bfred-it** [comment] 2017-09-13 16:42
Can you [pause on the exception](https://developers.google.com/web/updates/2015/05/automatically-pause-on-any-exception) and send me the value of `elFrom`?

It should be one of these two elements:

<img width="323" alt="notification-indicator" src="https://user-images.githubusercontent.com/1402241/30389508-389c3276-98dd-11e7-81cf-9dcf942504cb.png">
<img width="333" alt="mail-status" src="https://user-images.githubusercontent.com/1402241/30389509-38d406f6-98dd-11e7-9a1a-9259d51f25cf.png">

**Comment by bfred-it** [comment] 2017-09-13 16:44
Also it'd be great to see the entire HTML fetched in this tab:

<img width="776" alt="screen shot 2017-09-13 at 23 44 33" src="https://user-images.githubusercontent.com/1402241/30389592-78192d6e-98dd-11e7-9bed-e0ee4c98cfe9.png">

**Comment by yakov116** [comment] 2017-09-13 16:45
@bfred-it I just updated chrome. The issue is gone LOL

**Comment by bfred-it** [comment] 2017-09-13 16:46
I pushed a fix just to avoid the animation going on forever.

**Closed** 2017-09-13 16:47 UTC
